apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ramos-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-ramos
      color: blue
  template:
    metadata:
      labels:
        app: app-ramos
        color: blue
    spec:
      containers:
      - name: app-ramos
        image: sebastianvargas/app-ramos:stable
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
